version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app.db:/app/app.db
      - ./static/cimg:/app/static/cimg
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
